<a href="https://colab.research.google.com/github/alpbel0/AAD/blob/main/Nba_Games_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
from google.colab import drive
import pandas as pd
import sys

In [91]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [92]:

# Aşağıdaki yolu kendi Drive yapına göre güncelle!
module_path = '/content/drive/MyDrive/BitirmeProjesi'
if module_path not in sys.path:
    sys.path.append(module_path)


import data_processing

In [93]:
df_games = pd.read_csv("/content/drive/MyDrive/BitirmeProjesi/games.csv")
df_games_details = pd.read_csv("/content/drive/MyDrive/BitirmeProjesi/games_details.csv")
df_teams = pd.read_csv("/content/drive/MyDrive/BitirmeProjesi/teams.csv")
df_ranking = pd.read_csv("/content/drive/MyDrive/BitirmeProjesi/ranking.csv")
df_players = pd.read_csv("/content/drive/MyDrive/BitirmeProjesi/players.csv")

<ipython-input-93-5ec58b07da26>:2: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df_games_details = pd.read_csv("/content/drive/MyDrive/BitirmeProjesi/games_details.csv")

Veri setimiz ayrı ayrı csv dosyalarına yüklenmiş.Hepsini projemize yükledik.

Veri Setimizi tanıma amaçlı bir fonksiyon yazdık.

In [95]:
data_processing.summarize_dataframe(df_players, "players.csv")
data_processing.summarize_dataframe(df_games, "games.csv")
data_processing.summarize_dataframe(df_games_details, "games_details.csv")
data_processing.summarize_dataframe(df_teams, "teams.csv")
data_processing.summarize_dataframe(df_ranking, "ranking.csv")

--- players.csv ---

--- İlk 10 Satır (df.head(3)) ---
| PLAYER_NAME      |    TEAM_ID |   PLAYER_ID |   SEASON |
|:-----------------|-----------:|------------:|---------:|
| Royce O'Neale    | 1610612762 |     1626220 |     2019 |
| Bojan Bogdanovic | 1610612762 |      202711 |     2019 |
| Rudy Gobert      | 1610612762 |      203497 |     2019 |
| Donovan Mitchell | 1610612762 |     1628378 |     2019 |
| Mike Conley      | 1610612762 |      201144 |     2019 |
| Joe Ingles       | 1610612762 |      204060 |     2019 |
| Ed Davis         | 1610612762 |      202334 |     2019 |
| Jeff Green       | 1610612762 |      201145 |     2019 |
| Dante Exum       | 1610612762 |      203957 |     2019 |
| Emmanuel Mudiay  | 1610612762 |     1626144 |     2019 |

--- Veri Seti Bilgileri (df.info()) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7228 entries, 0 to 7227
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PLAYER_NAME  7228 non-null   object
 1   TEAM_ID      7228 non-null   int64
 2   PLAYER_ID    7228 non-null   int64
 3   SEASON       7228 non-null   int64
dtypes: int64(3), object(1)
memory usage: 226.0+ KB

--- Betimsel İstatistikler (df.describe()) ---
            TEAM_ID     PLAYER_ID       SEASON
count  7.228000e+03  7.228000e+03  7228.000000
mean   1.610613e+09  2.355862e+06  2014.159934
std    8.723521e+00  6.106688e+07     3.126216
min    1.610613e+09  2.440000e+02  2009.000000
25%    1.610613e+09  2.007680e+05  2012.000000
50%    1.610613e+09  2.023465e+05  2014.000000
75%    1.610613e+09  2.039100e+05  2017.000000
max    1.610613e+09  1.962938e+09  2019.000000

--- DataSet Boyutu (df.isnull().sum()) ---
(7228, 4)

--- Eksik Veri Sayıları (df.isnull().sum()) ---
PLAYER_NAME    0
TEAM_ID        0
PLAYER_ID      0
SEASON         0
dtype: int64

--- Sütun İsimleri ---
['PLAYER_NAME', 'TEAM_ID', 'PLAYER_ID', 'SEASON']

==================================================

--- games.csv ---

--- İlk 10 Satır (df.head(3)) ---
| GAME_DATE_EST   |   GAME_ID | GAME_STATUS_TEXT   |   HOME_TEAM_ID |   VISITOR_TEAM_ID |   SEASON |   TEAM_ID_home |   PTS_home |   FG_PCT_home |   FT_PCT_home |   FG3_PCT_home |   AST_home |   REB_home |   TEAM_ID_away |   PTS_away |   FG_PCT_away |   FT_PCT_away |   FG3_PCT_away |   AST_away |   REB_away |   HOME_TEAM_WINS |
|:----------------|----------:|:-------------------|---------------:|------------------:|---------:|---------------:|-----------:|--------------:|--------------:|---------------:|-----------:|-----------:|---------------:|-----------:|--------------:|--------------:|---------------:|-----------:|-----------:|-----------------:|
| 2022-12-22      |  22200477 | Final              |     1610612740 |        1610612759 |     2022 |     1610612740 |        126 |         0.484 |         0.926 |          0.382 |         25 |         46 |     1610612759 |        117 |         0.478 |         0.815 |          0.321 |         23 |         44 |                1 |
| 2022-12-22      |  22200478 | Final              |     1610612762 |        1610612764 |     2022 |     1610612762 |        120 |         0.488 |         0.952 |          0.457 |         16 |         40 |     1610612764 |        112 |         0.561 |         0.765 |          0.333 |         20 |         37 |                1 |
| 2022-12-21      |  22200466 | Final              |     1610612739 |        1610612749 |     2022 |     1610612739 |        114 |         0.482 |         0.786 |          0.313 |         22 |         37 |     1610612749 |        106 |         0.47  |         0.682 |          0.433 |         20 |         46 |                1 |
| 2022-12-21      |  22200467 | Final              |     1610612755 |        1610612765 |     2022 |     1610612755 |        113 |         0.441 |         0.909 |          0.297 |         27 |         49 |     1610612765 |         93 |         0.392 |         0.735 |          0.261 |         15 |         46 |                1 |
| 2022-12-21      |  22200468 | Final              |     1610612737 |        1610612741 |     2022 |     1610612737 |        108 |         0.429 |         1     |          0.378 |         22 |         47 |     1610612741 |        110 |         0.5   |         0.773 |          0.292 |         20 |         47 |                0 |
| 2022-12-21      |  22200469 | Final              |     1610612738 |        1610612754 |     2022 |     1610612738 |        112 |         0.386 |         0.84  |          0.317 |         26 |         62 |     1610612754 |        117 |         0.469 |         0.778 |          0.462 |         27 |         47 |                0 |
| 2022-12-21      |  22200470 | Final              |     1610612751 |        1610612744 |     2022 |     1610612751 |        143 |         0.643 |         0.875 |          0.636 |         42 |         32 |     1610612744 |        113 |         0.494 |         0.76  |          0.364 |         32 |         36 |                1 |
| 2022-12-21      |  22200471 | Final              |     1610612752 |        1610612761 |     2022 |     1610612752 |        106 |         0.553 |         0.611 |          0.423 |         25 |         38 |     1610612761 |        113 |         0.447 |         0.909 |          0.265 |         17 |         38 |                0 |
| 2022-12-21      |  22200472 | Final              |     1610612745 |        1610612753 |     2022 |     1610612745 |        110 |         0.466 |         0.647 |          0.395 |         22 |         49 |     1610612753 |        116 |         0.451 |         0.697 |          0.297 |         19 |         45 |                0 |
| 2022-12-21      |  22200473 | Final              |     1610612750 |        1610612742 |     2022 |     1610612750 |         99 |         0.494 |         0.7   |          0.267 |         23 |         39 |     1610612742 |        104 |         0.453 |         0.852 |          0.333 |         17 |         39 |                0 |

--- Veri Seti Bilgileri (df.info()) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26651 entries, 0 to 26650
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GAME_DATE_EST     26651 non-null  object
 1   GAME_ID           26651 non-null  int64
 2   GAME_STATUS_TEXT  26651 non-null  object
 3   HOME_TEAM_ID      26651 non-null  int64
 4   VISITOR_TEAM_ID   26651 non-null  int64
 5   SEASON            26651 non-null  int64
 6   TEAM_ID_home      26651 non-null  int64
 7   PTS_home          26552 non-null  float64
 8   FG_PCT_home       26552 non-null  float64
 9   FT_PCT_home       26552 non-null  float64
 10  FG3_PCT_home      26552 non-null  float64
 11  AST_home          26552 non-null  float64
 12  REB_home          26552 non-null  float64
 13  TEAM_ID_away      26651 non-null  int64
 14  PTS_away          26552 non-null  float64
 15  FG_PCT_away       26552 non-null  float64
 16  FT_PCT_away       26552 non-null  float64
 17  FG3_PCT_away      26552 non-null  float64
 18  AST_away          26552 non-null  float64
 19  REB_away          26552 non-null  float64
 20  HOME_TEAM_WINS    26651 non-null  int64
dtypes: float64(12), int64(7), object(2)
memory usage: 4.3+ MB

--- Betimsel İstatistikler (df.describe()) ---
            GAME_ID  HOME_TEAM_ID  VISITOR_TEAM_ID        SEASON  \
count  2.665100e+04  2.665100e+04     2.665100e+04  26651.000000
mean   2.175487e+07  1.610613e+09     1.610613e+09   2012.113879
std    5.570189e+06  8.638670e+00     8.659299e+00      5.587031
min    1.030000e+07  1.610613e+09     1.610613e+09   2003.000000
25%    2.070001e+07  1.610613e+09     1.610613e+09   2007.000000
50%    2.120076e+07  1.610613e+09     1.610613e+09   2012.000000
75%    2.180005e+07  1.610613e+09     1.610613e+09   2017.000000
max    5.210021e+07  1.610613e+09     1.610613e+09   2022.000000

       TEAM_ID_home      PTS_home   FG_PCT_home   FT_PCT_home  FG3_PCT_home  \
count  2.665100e+04  26552.000000  26552.000000  26552.000000  26552.000000
mean   1.610613e+09    103.455898      0.460735      0.760377      0.356023
std    8.638670e+00     13.283370      0.056676      0.100677      0.111164
min    1.610613e+09     36.000000      0.250000      0.143000      0.000000
25%    1.610613e+09     94.000000      0.422000      0.697000      0.286000
50%    1.610613e+09    103.000000      0.460000      0.765000      0.357000
75%    1.610613e+09    112.000000      0.500000      0.833000      0.429000
max    1.610613e+09    168.000000      0.684000      1.000000      1.000000

           AST_home      REB_home  TEAM_ID_away      PTS_away   FG_PCT_away  \
count  26552.000000  26552.000000  2.665100e+04  26552.000000  26552.000000
mean      22.823441     43.374284  1.610613e+09    100.639876      0.449732
std        5.193308      6.625769  8.659299e+00     13.435868      0.055551
min        6.000000     15.000000  1.610613e+09     33.000000      0.244000
25%       19.000000     39.000000  1.610613e+09     91.000000      0.412000
50%       23.000000     43.000000  1.610613e+09    100.000000      0.449000
75%       26.000000     48.000000  1.610613e+09    110.000000      0.487000
max       50.000000     72.000000  1.610613e+09    168.000000      0.687000

        FT_PCT_away  FG3_PCT_away      AST_away      REB_away  HOME_TEAM_WINS
count  26552.000000  26552.000000  26552.000000  26552.000000    26651.000000
mean       0.758816      0.349489     21.496271     42.113249        0.587032
std        0.103429      0.109441      5.160596      6.533039        0.492376
min        0.143000      0.000000      4.000000     19.000000        0.000000
25%        0.692000      0.278000     18.000000     38.000000        0.000000
50%        0.765000      0.350000     21.000000     42.000000        1.000000
75%        0.833000      0.419000     25.000000     46.000000        1.000000
max        1.000000      1.000000     46.000000     81.000000        1.000000

--- DataSet Boyutu (df.isnull().sum()) ---
(26651, 21)

--- Eksik Veri Sayıları (df.isnull().sum()) ---
GAME_DATE_EST        0
GAME_ID              0
GAME_STATUS_TEXT     0
HOME_TEAM_ID         0
VISITOR_TEAM_ID      0
SEASON               0
TEAM_ID_home         0
PTS_home            99
FG_PCT_home         99
FT_PCT_home         99
FG3_PCT_home        99
AST_home            99
REB_home            99
TEAM_ID_away         0
PTS_away            99
FG_PCT_away         99
FT_PCT_away         99
FG3_PCT_away        99
AST_away            99
REB_away            99
HOME_TEAM_WINS       0
dtype: int64

--- Sütun İsimleri ---
['GAME_DATE_EST', 'GAME_ID', 'GAME_STATUS_TEXT', 'HOME_TEAM_ID', 'VISITOR_TEAM_ID', 'SEASON', 'TEAM_ID_home', 'PTS_home', 'FG_PCT_home', 'FT_PCT_home', 'FG3_PCT_home', 'AST_home', 'REB_home', 'TEAM_ID_away', 'PTS_away', 'FG_PCT_away', 'FT_PCT_away', 'FG3_PCT_away', 'AST_away', 'REB_away', 'HOME_TEAM_WINS']

==================================================

--- games_details.csv ---

--- İlk 10 Satır (df.head(3)) ---
|   GAME_ID |    TEAM_ID | TEAM_ABBREVIATION   | TEAM_CITY   |   PLAYER_ID | PLAYER_NAME      | NICKNAME   | START_POSITION   |   COMMENT | MIN   |   FGM |   FGA |   FG_PCT |   FG3M |   FG3A |   FG3_PCT |   FTM |   FTA |   FT_PCT |   OREB |   DREB |   REB |   AST |   STL |   BLK |   TO |   PF |   PTS |   PLUS_MINUS |
|----------:|-----------:|:--------------------|:------------|------------:|:-----------------|:-----------|:-----------------|----------:|:------|------:|------:|---------:|-------:|-------:|----------:|------:|------:|---------:|-------:|-------:|------:|------:|------:|------:|-----:|-----:|------:|-------------:|
|  22200477 | 1610612759 | SAS                 | San Antonio |     1629641 | Romeo Langford   | Romeo      | F                |       nan | 18:06 |     1 |     1 |    1     |      0 |      0 |     0     |     0 |     0 |    0     |      1 |      1 |     2 |     0 |     1 |     0 |    2 |    5 |     2 |           -2 |
|  22200477 | 1610612759 | SAS                 | San Antonio |     1631110 | Jeremy Sochan    | Jeremy     | F                |       nan | 31:01 |     7 |    14 |    0.5   |      2 |      4 |     0.5   |     7 |    10 |    0.7   |      6 |      3 |     9 |     6 |     1 |     0 |    2 |    1 |    23 |          -14 |
|  22200477 | 1610612759 | SAS                 | San Antonio |     1627751 | Jakob Poeltl     | Jakob      | C                |       nan | 21:42 |     6 |     9 |    0.667 |      0 |      0 |     0     |     1 |     1 |    1     |      1 |      3 |     4 |     1 |     1 |     0 |    2 |    4 |    13 |           -4 |
|  22200477 | 1610612759 | SAS                 | San Antonio |     1630170 | Devin Vassell    | Devin      | G                |       nan | 30:20 |     4 |    13 |    0.308 |      1 |      6 |     0.167 |     1 |     1 |    1     |      0 |      9 |     9 |     5 |     3 |     0 |    2 |    1 |    10 |          -18 |
|  22200477 | 1610612759 | SAS                 | San Antonio |     1630200 | Tre Jones        | Tre        | G                |       nan | 27:44 |     7 |    12 |    0.583 |      1 |      3 |     0.333 |     4 |     4 |    1     |      0 |      2 |     2 |     3 |     0 |     0 |    2 |    2 |    19 |            0 |
|  22200477 | 1610612759 | SAS                 | San Antonio |     1628380 | Zach Collins     | Zach       | nan              |       nan | 18:04 |     2 |     6 |    0.333 |      0 |      0 |     0     |     2 |     2 |    1     |      1 |      1 |     2 |     2 |     0 |     0 |    0 |    3 |     6 |          -13 |
|  22200477 | 1610612759 | SAS                 | San Antonio |      203926 | Doug McDermott   | Doug       | nan              |       nan | 16:55 |     2 |     8 |    0.25  |      1 |      5 |     0.2   |     0 |     0 |    0     |      1 |      3 |     4 |     1 |     0 |     0 |    1 |    0 |     5 |          -10 |
|  22200477 | 1610612759 | SAS                 | San Antonio |     1626196 | Josh Richardson  | Josh       | nan              |       nan | 21:20 |     5 |    11 |    0.455 |      2 |      5 |     0.4   |     2 |     3 |    0.667 |      1 |      2 |     3 |     3 |     0 |     0 |    1 |    2 |    14 |           -2 |
|  22200477 | 1610612759 | SAS                 | San Antonio |     1631103 | Malaki Branham   | Malaki     | nan              |       nan | 21:10 |     4 |     6 |    0.667 |      1 |      3 |     0.333 |     0 |     0 |    0     |      0 |      0 |     0 |     0 |     0 |     0 |    1 |    2 |     9 |           -6 |
|  22200477 | 1610612759 | SAS                 | San Antonio |     1628966 | Keita Bates-Diop | Keita      | nan              |       nan | 9:16  |     1 |     3 |    0.333 |      0 |      0 |     0     |     2 |     2 |    1     |      1 |      0 |     1 |     0 |     0 |     0 |    0 |    1 |     4 |           -1 |

--- Veri Seti Bilgileri (df.info()) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 668628 entries, 0 to 668627
Data columns (total 29 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   GAME_ID            668628 non-null  int64
 1   TEAM_ID            668628 non-null  int64
 2   TEAM_ABBREVIATION  668628 non-null  object
 3   TEAM_CITY          668628 non-null  object
 4   PLAYER_ID          668628 non-null  int64
 5   PLAYER_NAME        668628 non-null  object
 6   NICKNAME           53037 non-null   object
 7   START_POSITION     255765 non-null  object
 8   COMMENT            109689 non-null  object
 9   MIN                558938 non-null  object
 10  FGM                558938 non-null  float64
 11  FGA                558938 non-null  float64
 12  FG_PCT             558938 non-null  float64
 13  FG3M               558938 non-null  float64
 14  FG3A               558938 non-null  float64
 15  FG3_PCT            558938 non-null  float64
 16  FTM                558938 non-null  float64
 17  FTA                558938 non-null  float64
 18  FT_PCT             558938 non-null  float64
 19  OREB               558938 non-null  float64
 20  DREB               558938 non-null  float64
 21  REB                558938 non-null  float64
 22  AST                558938 non-null  float64
 23  STL                558938 non-null  float64
 24  BLK                558938 non-null  float64
 25  TO                 558938 non-null  float64
 26  PF                 558938 non-null  float64
 27  PTS                558938 non-null  float64
 28  PLUS_MINUS         535277 non-null  float64
dtypes: float64(19), int64(3), object(7)
memory usage: 147.9+ MB

--- Betimsel İstatistikler (df.describe()) ---
            GAME_ID       TEAM_ID     PLAYER_ID            FGM            FGA  \
count  6.686280e+05  6.686280e+05  6.686280e+05  558938.000000  558938.000000
mean   2.171771e+07  1.610613e+09  4.013434e+05       3.588446       7.896652
std    5.656289e+06  8.652260e+00  7.225618e+06       3.030466       5.677002
min    1.030000e+07  1.610613e+09  1.500000e+01       0.000000       0.000000
25%    2.070003e+07  1.610613e+09  2.466000e+03       1.000000       3.000000
50%    2.120096e+07  1.610613e+09  2.011810e+05       3.000000       7.000000
75%    2.180014e+07  1.610613e+09  2.034710e+05       5.000000      11.000000
max    5.210021e+07  1.610613e+09  1.962938e+09      28.000000      50.000000

              FG_PCT           FG3M           FG3A        FG3_PCT  \
count  558938.000000  558938.000000  558938.000000  558938.000000
mean        0.416842       0.778117       2.186019       0.201032
std         0.251913       1.227615       2.569913       0.289685
min         0.000000       0.000000       0.000000       0.000000
25%         0.267000       0.000000       0.000000       0.000000
50%         0.429000       0.000000       1.000000       0.000000
75%         0.571000       1.000000       4.000000       0.400000
max         1.000000      14.000000      24.000000       1.000000

                 FTM  ...           OREB           DREB           REB  \
count  558938.000000  ...  558938.000000  558938.000000  558938.00000
mean        1.733217  ...       1.024212       3.033798       4.05801
std         2.353981  ...       1.397830       2.687384       3.48250
min         0.000000  ...       0.000000       0.000000       0.00000
25%         0.000000  ...       0.000000       1.000000       1.00000
50%         1.000000  ...       1.000000       2.000000       3.00000
75%         3.000000  ...       2.000000       4.000000       6.00000
max        26.000000  ...      18.000000      25.000000      31.00000

                 AST            STL            BLK             TO  \
count  558938.000000  558938.000000  558938.000000  558938.000000
mean        2.103958       0.721436       0.460339       1.320297
std         2.475476       0.972231       0.860962       1.402329
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         1.000000       0.000000       0.000000       1.000000
75%         3.000000       1.000000       1.000000       2.000000
max        25.000000      10.000000      12.000000      12.000000

                  PF            PTS     PLUS_MINUS
count  558938.000000  558938.000000  535277.000000
mean        1.999538       9.688218      -0.000488
std         1.502963       8.082152      10.665573
min         0.000000       0.000000     -57.000000
25%         1.000000       3.000000      -7.000000
50%         2.000000       8.000000       0.000000
75%         3.000000      14.000000       6.000000
max        15.000000      81.000000      57.000000

[8 rows x 22 columns]

--- DataSet Boyutu (df.isnull().sum()) ---
(668628, 29)

--- Eksik Veri Sayıları (df.isnull().sum()) ---
GAME_ID                   0
TEAM_ID                   0
TEAM_ABBREVIATION         0
TEAM_CITY                 0
PLAYER_ID                 0
PLAYER_NAME               0
NICKNAME             615591
START_POSITION       412863

# **BURAYA HER BİR SÜTUNUN AÇIKLAMASINI YAZ.**

In [96]:
data_files = [df_games, df_games_details, df_teams, df_ranking, df_players]
names      = ["games", "games_details", "teams", "ranking", "players"]

data_processing.analyze_missing_values(data_files, data_names=names)

--- 'games' için eksik veri analizi ---
              Eksik Değer Sayısı  Eksik Yüzdesi (%)
PTS_home                      99           0.371468
FG_PCT_home                   99           0.371468
FT_PCT_home                   99           0.371468
FG3_PCT_home                  99           0.371468
AST_home                      99           0.371468
REB_home                      99           0.371468
PTS_away                      99           0.371468
FG_PCT_away                   99           0.371468
FT_PCT_away                   99           0.371468
FG3_PCT_away                  99           0.371468
AST_away                      99           0.371468
REB_away                      99           0.371468

--- 'games_details' için eksik veri analizi ---
                Eksik Değer Sayısı  Eksik Yüzdesi (%)
NICKNAME                    615591          92.067787
COMMENT                     558939          83.594914
START_POSITION              412863          61.747788
PLUS_MINUS                  133351          19.943975
MIN                         109690          16.405236
FGA                         109690          16.405236
FGM                         109690          16.405236
FG_PCT                      109690          16.405236
FG3M                        109690          16.405236
FG3_PCT                     109690          16.405236
FG3A                        109690          16.405236
FTA                         109690          16.405236
FT_PCT                      109690          16.405236
OREB                        109690          16.405236
FTM                         109690          16.405236
DREB                        109690          16.405236
REB                         109690          16.405236
STL                         109690          16.405236
AST                         109690          16.405236
BLK                         109690          16.405236
TO                          109690          16.405236
PF                          109690          16.405236
PTS                         109690          16.405236

--- 'teams' için eksik veri analizi ---
               Eksik Değer Sayısı  Eksik Yüzdesi (%)
ARENACAPACITY                   4          13.333333

--- 'ranking' için eksik veri analizi ---
              Eksik Değer Sayısı  Eksik Yüzdesi (%)
RETURNTOPLAY              206352          98.103089

--- 'players' için eksik veri analizi ---
Bu DataFrame'de hiç eksik veri yok. Harika!

Eksik verilerin analizini de yaptık şimdi bunları doldurma işlemine geçeceğiz.